import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
    await page.goto('/')
    await page.getByText('Owners').click()
    await page.getByRole('link', { name: 'Search' }).click()
})

test('Select the desired date in the calendar', async ({ page }) => {
    await page.getByRole('link', { name: 'Harold Davis' }).click()
    await page.getByRole('button', { name: 'Add New Pet' }).click()
    await expect(page.locator('.glyphicon-remove').nth(0)).toBeVisible()
    await page.getByRole('textbox', { name: 'Name' }).fill('Tom')
    await expect(page.locator('.glyphicon-ok').nth(0)).toBeVisible()
    await page.locator('button').nth(0).click()
    await page.locator('.mat-calendar-period-button').click()
    await page.locator('.mat-calendar-previous-button').click()
    await page.locator('button', { has: page.locator('span', { hasText: '2014' }) }).click()
    await page.locator('button', { has: page.locator('span', { hasText: 'MAY' }) }).click()
    const allDates = page.locator('td button')
    await allDates.getByText('2', { exact: true }).click()
    await expect(page.locator('[name="birthDate"]')).toHaveValue('2014/05/02')
    await page.locator('select').selectOption('dog')
    await page.getByRole('button', { name: 'Save Pet' }).click()
    const petInfo = page.locator('app-pet-list', { has: page.getByText('Tom') })
    await expect(petInfo.locator('dd').nth(1)).toHaveText('2014-05-02')
    await petInfo.getByRole('button', { name: 'Delete Pet' }).click()
    await page.waitForResponse('**/pets/**')
    await expect(petInfo).toHaveCount(0)
})

test('Select the dates of the visit and validate dates order', async ({ page }) => {
    await page.getByRole('link', { name: 'Jean Coleman' }).click()
    const samanthaPetInfo = page.locator('app-pet-list', { has: page.getByText('Samantha') })
    await samanthaPetInfo.getByRole('button', { name: 'Add Visit' }).click()
    await expect(page.getByRole('heading')).toHaveText('New Visit')
    await expect(page.locator('table').nth(0).locator('tr td').nth(0)).toHaveText('Samantha')
    await expect(page.locator('table').nth(0).locator('tr td').nth(3)).toHaveText('Jean Coleman')
    await page.locator('[aria-label="Open calendar"]').click()
    await page.locator('.mat-calendar-body-today').click()
    const date = new Date()
    let yyyy = date.getFullYear()
    let mm = String(date.getMonth() + 1).padStart(2, '0')
    let dd = String(date.getDate()).padStart(2, '0')
    await expect(page.locator('[name="date"]')).toHaveValue(`${yyyy}/${mm}/${dd}`)
    await page.locator('#description').fill('dermatologists visit')
    await page.getByRole('button', { name: 'Add Visit' }).click()
    await expect(samanthaPetInfo.locator('app-visit-list tr').nth(1).locator('td').nth(0)).toHaveText(`${yyyy}-${mm}-${dd}`)
    await samanthaPetInfo.getByRole('button', { name: 'Add Visit' }).click()
    await page.locator('[aria-label="Open calendar"]').click()
    date.setDate(date.getDate() - 45)
    yyyy = date.getFullYear()
    mm = String(date.getMonth() + 1).padStart(2, '0')
    dd = date.getDate().toString()
    const expectedMMYYYY = `${mm} ${yyyy}`
    let actualMMYYYY = await page.locator('.mat-calendar-period-button').textContent()
    while (expectedMMYYYY != actualMMYYYY) {
        await page.locator('[aria-label="Previous month"]').click()
        actualMMYYYY = await page.locator('.mat-calendar-period-button').textContent()
    }
    await page.locator('.mat-calendar-body-cell').getByText(dd, { exact: true }).click()
    await page.locator('#description').fill('massage therapy')
    await page.getByRole('button', { name: 'Add Visit' }).click()

    const dermatologistsVisitRow = samanthaPetInfo.locator('app-visit-list tr', { hasText: 'dermatologists visit' })
    const messageTheraphyVisitRow = samanthaPetInfo.locator('app-visit-list tr', { hasText: 'massage therapy' })
    const dermatologistsVisitDate = await dermatologistsVisitRow.locator('td').nth(0).textContent()
    const messageTheraphyVisitDate = await messageTheraphyVisitRow.locator('td').nth(0).textContent()
    expect(new Date(dermatologistsVisitDate!) > new Date(messageTheraphyVisitDate!)).toBeTruthy()

    await dermatologistsVisitRow.getByRole('button', { name: 'Delete Visit' }).click()
    await messageTheraphyVisitRow.getByRole('button', { name: 'Delete Visit' }).click()
    await expect(dermatologistsVisitRow).toHaveCount(0)
    await expect(messageTheraphyVisitRow).toHaveCount(0)
})
