import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByText('Pet Types').click()
  await expect(page.locator('h2')).toHaveText('Pet Types')
})

test('Update pet type', async ({ page }) => {
  const catPetRow = page.locator('tbody tr').filter({ has: page.locator('input[id="0"]') })
  const editButton = catPetRow.getByRole('button', { name: 'Edit' })
  await editButton.click()
  await expect(page.locator('h2')).toHaveText('Edit Pet Type')
  await page.waitForResponse('**/pettypes/**')
  const editTextbox = page.locator('input[required]')
  await editTextbox.fill('rabbit')
  const updateButton = page.getByRole('button', { name: 'Update' })
  await updateButton.click()
  const petTextBox = catPetRow.getByRole('textbox')
  await expect(petTextBox).toHaveValue('rabbit')
  await editButton.click()
  await page.waitForResponse('**/pettypes/**')
  await editTextbox.fill('cat')
  await updateButton.click()
  await expect(petTextBox).toHaveValue('cat')
})

test('Cancel pet type update', async ({ page }) => {
  const dogPetRow = page.locator('tbody tr').filter({ has: page.locator('input[id="1"]') })
  const editButton = dogPetRow.getByRole('button', { name: 'Edit' })
  await editButton.click()
  await page.waitForResponse('**/pettypes/**')
  const editTextbox = page.locator('input[required]')
  await editTextbox.fill('moose')
  await expect(editTextbox).toHaveValue('moose')
  const cancelButton = page.getByRole('button', { name: 'Cancel' })
  await cancelButton.click()
  const petTextBox = dogPetRow.getByRole('textbox')
  await expect(petTextBox).toHaveValue('dog')
})

test.only('Validation of pet type name is required', async ({ page }) => {
  const lizardPetRow = page.locator('tbody tr').filter({ has: page.locator('input[id="2"]') })
  const editButton = lizardPetRow.getByRole('button', { name: 'Edit' })
  await editButton.click()
  await page.waitForResponse('**/pettypes/**')
  const editTextbox = page.locator('input[required]')
  await editTextbox.clear()
  await expect(page.locator('.help-block')).toHaveText('Name is required')
  const updateButton = page.getByRole('button', { name: 'Update' })
  await updateButton.click()
  await expect(page.locator('h2')).toHaveText('Edit Pet Type')
  const cancelButton = page.getByRole('button', { name: 'Cancel' })
  await cancelButton.click()
  const petTextBox = lizardPetRow.getByRole('textbox')
  await expect(petTextBox).toHaveValue('lizard')
})